name: deployment test
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize

jobs:
  deployment-test:
    strategy:
      matrix:
        test:
          - a
          - b
    uses: ./.github/workflows/reusable-deployment-test.yml

