name: workflow call test
on:
  pull_request:
  workflow_dispatch:

jobs:
  reusable_workflow_job:
    strategy:
      matrix:
        test:
          - hoge
          - fuga
    uses: srz-zumix/gh-act-on/.github/workflows/events.yml@main
    with:
      username: ${{ github.actor }}
    secrets: inherit
